name: CI for AnvilCraftMod
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_BUILD: true
      HOTFIX_BUILD: true
      PR_BUILD: false
      VERSION_TYPE: beta
    steps:
      - name: gametest
        uses: Gu-ZT/action-test@main
        continue-on-error: false
        with:
          mod: mods/anvilcraft-neoforge-1.21.1-1.5.0.jar
          extra-mods: |
            create:mc1.21.1-6.0.9
            patchouli:1.21.1-92-neoforge
          maven-repos: |
            https://server.cjsah.net:1002/maven
            https://maven.createmod.net
          maven-mods: |
            dev.anvilcraft.lib:anvillib-neoforge-1.21.1:1.4.0+build.172
            net.createmod.ponder:Ponder-NeoForge-1.21.1:1.0.69
          url-mods: |
            https://maven.latvian.dev/releases/dev/latvian/mods/rhino-neoforge/2006.2.4-build.17/rhino-neoforge-2006.2.4-build.17.jar
            https://maven.latvian.dev/releases/dev/latvian/mods/kubejs-neoforge/2101.7.2-build.351/kubejs-neoforge-2101.7.2-build.351.jar
          other-files: |
            resources@https://cdn.modrinth.com/data/MoyjiexA/versions/Kf4o6AQb/Strong%20male%20basic%20color.zip
